spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/aiactivityfitness
      database: aiactivityfitness

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  redis:
    host: localhost
    port: 6379
    timeout: 2000
  cache:
    type: redis

#logging:
#  level:
#    io.lettuce.core: DEBUG
#    org.springframework.cache: TRACE
#    org.springframework.data.redis: DEBUG

kafka:
  topic:
    activity-created: activity-created-events
    activity-deleted: activity-deleted-events


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8082