spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/ai_recommendation_fitness
      database: ai_recommendation_fitness

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: activity-consumer-group
      auto-offset-reset: earliest

#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

      properties:
        spring:
          deserializer:
            key:
              delegate:
                class: org.apache.kafka.common.serialization.StringDeserializer
            value:
              delegate:
                class: org.springframework.kafka.support.serializer.JsonDeserializer
          json:
            use:
              type:
                headers: false
#            value:
#              default:
#                type: com.fitness.aiservice.models.Activity
            trusted:
              packages: "*"

kafka:
  topic:
    activity-created: activity-created-events
    activity-deleted: activity-deleted-events

gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8083
