spring:
  application:
    name: userservice
  datasource:
    url: jdbc:postgresql://localhost:5435/fitness-micro-user
    username: postgres
    password: 4321

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
