spring:
  application:
    name: fitnessAppConfigserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-location: classpath:/config

server:
  port: 8888